# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constrs/io.xdc

# XDC: imports/constrs/timing.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_0_0 || ORIG_REF_NAME==system_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Note_Driver_0_0/system_Note_Driver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Note_Driver_0_0 || ORIG_REF_NAME==system_Note_Driver_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Note_Config_0_0/system_Note_Config_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Note_Config_0_0 || ORIG_REF_NAME==system_Note_Config_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Note_Generator_0_0/system_Note_Generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Note_Generator_0_0 || ORIG_REF_NAME==system_Note_Generator_0_0} -quiet] -quiet

# IP: bd/system/ip/system_I2S_Tx_0_0/system_I2S_Tx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_I2S_Tx_0_0 || ORIG_REF_NAME==system_I2S_Tx_0_0} -quiet] -quiet

# IP: bd/system/ip/system_NCA_0_0/system_NCA_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_NCA_0_0 || ORIG_REF_NAME==system_NCA_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Debounce_Switch_0_0/system_Debounce_Switch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Debounce_Switch_0_0 || ORIG_REF_NAME==system_Debounce_Switch_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Debounce_Switch_1_0/system_Debounce_Switch_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Debounce_Switch_1_0 || ORIG_REF_NAME==system_Debounce_Switch_1_0} -quiet] -quiet

# IP: bd/system/ip/system_Debounce_Switch_2_0/system_Debounce_Switch_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Debounce_Switch_2_0 || ORIG_REF_NAME==system_Debounce_Switch_2_0} -quiet] -quiet

# IP: bd/system/ip/system_Debounce_Switch_3_0/system_Debounce_Switch_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Debounce_Switch_3_0 || ORIG_REF_NAME==system_Debounce_Switch_3_0} -quiet] -quiet

# XDC: c:/Users/anton/Desktop/RTLogik/Repositories/Zynth/workspace/vivado_ws/Zynth.gen/sources_1/bd/system/system_ooc.xdc
