# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/anton/Desktop/RTLogik/Repositories/Zynth/workspace/vivado_ws/Zynth.srcs/sources_1/bd/system/ip/system_NCA_0_0/system_NCA_0_0.xci
# IP: The module: 'system_NCA_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/anton/Desktop/RTLogik/Repositories/Zynth/workspace/vivado_ws/Zynth.gen/sources_1/bd/system/ip/system_NCA_0_0/src/NCA_mult_gen_0_0/NCA_mult_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==NCA_mult_gen_0_0 || ORIG_REF_NAME==NCA_mult_gen_0_0} -quiet] -quiet

# IP: c:/Users/anton/Desktop/RTLogik/Repositories/Zynth/workspace/vivado_ws/Zynth.gen/sources_1/bd/system/ip/system_NCA_0_0/src/NCA_mult_gen_1_0/NCA_mult_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==NCA_mult_gen_1_0 || ORIG_REF_NAME==NCA_mult_gen_1_0} -quiet] -quiet

# XDC: c:/Users/anton/Desktop/RTLogik/Repositories/Zynth/workspace/vivado_ws/Zynth.gen/sources_1/bd/system/ip/system_NCA_0_0/src/NCA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_NCA_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/anton/Desktop/RTLogik/Repositories/Zynth/workspace/vivado_ws/Zynth.srcs/sources_1/bd/system/ip/system_NCA_0_0/system_NCA_0_0.xci
# IP: The module: 'system_NCA_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/anton/Desktop/RTLogik/Repositories/Zynth/workspace/vivado_ws/Zynth.gen/sources_1/bd/system/ip/system_NCA_0_0/src/NCA_mult_gen_0_0/NCA_mult_gen_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==NCA_mult_gen_0_0 || ORIG_REF_NAME==NCA_mult_gen_0_0} -quiet] -quiet

# IP: c:/Users/anton/Desktop/RTLogik/Repositories/Zynth/workspace/vivado_ws/Zynth.gen/sources_1/bd/system/ip/system_NCA_0_0/src/NCA_mult_gen_1_0/NCA_mult_gen_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==NCA_mult_gen_1_0 || ORIG_REF_NAME==NCA_mult_gen_1_0} -quiet] -quiet

# XDC: c:/Users/anton/Desktop/RTLogik/Repositories/Zynth/workspace/vivado_ws/Zynth.gen/sources_1/bd/system/ip/system_NCA_0_0/src/NCA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_NCA_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
